# 服务配置
server:
  port: 8084
spring:
  # 环境
  profiles:
    active: dev
  # 项目配置
  application:
    name: nowander-oss
  mvc:
    static-path-pattern: /**
  redis:
    host: 119.23.214.198
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
    client-type: lettuce
    timeout: 1800000
    password: ENC(0LWEduGcDiVdrOd8Xk7qHWmcOgXKEzcNKAbef4sp19MakUA4ozqtN/h1g+X2NmtZcSnCxmp1JCsjZglkSREh9g==)
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public

logging:
  config: classpath:log4j2.xml
  level:
    root: debug

app:
  file:
    oss:
      endpoint: http://oss-cn-guangzhou.aliyuncs.com
      bucket-name: nowander
      access-key-id: ENC(nO9voXvLnOwDOv/5xvn4thwHZ+B/umQVLIEVIUGpl/d8dzTS6S3FIdvSAWDIPpYSnzdCnZsuiQ2GexiBql5wxA==)
      access-key-secret: ENC(E4meUUc8L6CpICrcXNBGiSVQ0sBBBbXAPdEaRGW4suTJLi94vzgVrAyIm2V52eantbhdU8kyv76syqGBf3kIFA==)
    path-separator: /
  lock:
    redis:
      key-prefix: nowander:oss:lock