# 服务配置
server:
  port: 8083
spring:
  # 项目配置
  application:
    name: nowander-captcha
  profiles:
    active: dev

  mvc:
    static-path-pattern: /**

  # redis配置
  redis:
    host: 119.23.214.198
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
    client-type: lettuce
    timeout: 1800000
    password: ENC(0LWEduGcDiVdrOd8Xk7qHWmcOgXKEzcNKAbef4sp19MakUA4ozqtN/h1g+X2NmtZcSnCxmp1JCsjZglkSREh9g==)

  # 数据源配置
  datasource:
    url: jdbc:mysql://119.23.214.198:3306/nowander?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: nowander_user
    password: ENC(Z32pHse78n2YDRMpct2Q/mFbSKjDxFmFqVpjRkc4kSW9i/x21yzI3S5C6tocw4pX7V8ZcDdweq9g+lk5vyiExg==)
    driver-class-name: com.mysql.cj.jdbc.Driver

    # druid配置
    druid:
      aop-patterns: com.atguigu.admin.*  # 监控这个包下的所有spring组件
      filters: stat,wall,slf4j  # 开启的功能，需要再配置具体的filter

      stat-view-servlet: # 监控页配置
        enabled: true # 默认没有开启
        login-username: admin # 登录页限制登录用户
        login-password: admin
        resetEnable: false

      web-stat-filter: #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: # sql监控
          slow-sql-millis: 1000 # 超过1000ms的查询都是慢查询
          logSlowSql: true
          enabled: true
        wall: # 防火墙
          enabled: true
          config:
            drop-table-allow: false # 禁止删除表操作
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public
  elasticsearch:
    uris: http://119.23.214.198:9200

# mybatisplus配置
mybatis-plus:
  type-handlers-package: com.nowander.common.core.repository
  type-enums-package: com.nowander.common.core.enums
  mapper-locations: classpath*:mapper/*.xml
  configuration: # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  config: classpath:log4j2.xml
  level:
    root: debug

app:
  lock:
    redis:
      key-prefix: nowander:captcha:lock